# https://taskfile.dev

version: "3"

vars:
  DEFAULT_THEME: jsonresume-theme-kendall
  HTML: ./static/cv.html

tasks:
  default:
    cmds:
      - task --list
    silent: true

  dev:
    desc: Set up the dev environment
    cmds:
      - bun install

  build:
    desc: Build the site locally
    cmds:
      - rm -rf public
      - bun x resumed render --theme {{.DEFAULT_THEME}} --output {{.HTML}}
      - hugo build --buildDrafts --minify

  serve:
    desc: Build and serve locally
    deps:
      - build
    cmds:
      - open "http://localhost:1313/"
      - hugo server --buildDrafts

  check:
    desc: Check content for typos
    preconditions:
      - sh: command -v typos
        msg: typos CLI not installed, see https://github.com/crate-ci/typos?tab=readme-ov-file#install
    cmds:
      - typos --config .typos.toml
      - bun x resumed validate

  update:
    desc: Update theme
    cmds:
      - git submodule update --remote --merge
      - git submodule foreach git pull origin main

  post:
    desc: Create a new post
    cmds:
      - hugo new --kind post content/posts/{{.CLI_ARGS}}/index.md
